version: '3'
services:
    node:
      build: .
      ports: 
        - ${PORT}:${PORT}
      depends_on:
        - postgres
      environment: 
        - PORT=${PORT}
      volumes:
        - /app/node_modules
        - .:/app
      restart: always
      networks:
        - mynetwork
    postgres:
      build: ./database/
      volumes:
        - ./postgre:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      restart: always
      networks:
        - mynetwork
      environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
networks:
  mynetwork:
    driver: bridge